<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LOGO</name>
   <tag></tag>
   <elementGuidId>cc721a05-8a99-49b2-bc78-a8774b3b81b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='logo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='logo']</value>
      <webElementGuid>a4f9fc1d-14a7-4071-96c2-4c8e45a6c3b7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
