<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Plus_Quantity</name>
   <tag></tag>
   <elementGuidId>310f9cac-6ff8-401f-8b29-2bcc2d242052</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='plus']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='plus']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='plus']</value>
      <webElementGuid>e7d2604e-152d-4589-946a-08bb058a749f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
